### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by KennethNagin** [ibm-messaging/kafka-connect-ibmcos-sink#10]
Do you have a helm chart for installing into k8s?

**Comment by mimaison** [comment]
Hi @KennethNagin,

In our [samples repo](https://github.com/ibm-messaging/event-streams-samples), we have a YAML file and instructions for deploying an image including this connector to Kubernetes, see https://github.com/ibm-messaging/event-streams-samples/tree/master/kafka-connect/IKS

**Comment by jhughes24816** [comment]
Given the age of this issue I am going to close it shortly. If there are follow up questions please raise a new issue and reference the conversation here. Thanks.
