### ISSUE TITLE
Feature request: Add newlines for each event to be uploaded to COS

### ISSUE THREAD

**Issue by lijs-cn** [ibm-messaging/kafka-connect-ibmcos-sink#4]
We are using kafka cos sink connector to store events from eventstream to COS(which is really a helpful tool), then analyses data from COS using `IBM SQL query`, 

with help from @dpittner from SQL query team, we found that the COS object uploaded using kafka cos connector can not be correctly processed by SQL query, since there’s no newline for each json object within the same cos file, instead, all the json objects are in one single line. 

To be correctly processed by SQL Query, need to add new lines for each event(json object).  

This issue is a feature request to at least add an option to make it configurable.

**Comment by mimaison** [comment]
Fixed in #5, closing
